#settings:
  # Whether or not Mining Fatigue -1 should be permanently applied to players.
  # WARNING: Will prevent players from breaking blocks that aren't configured by Breaker!
  #permanent-mining-fatigue: false

debug:
  enabled: false
  depth: 0