#settings:
  # Whether or not Mining Fatigue -1 should be permanently applied to players.
  # WARNING: Will prevent players from breaking blocks that aren't configured by Breaker!
  #permanent-mining-fatigue: false

#The material to modify.
STONE:
  #The block break speed (in ticks) if no state is present.
  hardness: 50
LOG:
  hardness: 50
LOG:1:
  hardness: 50