name: Breaker
main: com.github.xhexed.breaker.Breaker
version: ${project.version}
depend: [ProtocolLib]
commands:
  breaker:
    usage: /breaker
    description: Master command for all Breaker commands.
    permission: breaker.admin
permissions:
  breaker.admin:
    description: Allows usage of all Breaker commands.
    default: op